config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  resources :dealerships 
  resources :inventories
  #get 'home/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dealership.rb
class Dealership < ApplicationRecord

    has_many :inventories
    belongs_to :user

  def to_s
    name
end
end

app/models/inventory.rb
class Inventory < ApplicationRecord

    belongs_to :dealership
    validates :status, inclusion: { in: %w[old new] }
  
    STATUS_OPTIONS = [
      %w[New new],
      %w[Old old]
    ].freeze
  
  
    def monthly_price
      time = Time.now
      if time.month <= 12 && !price.nil?
        (1..time.month).each do |_i|
          self.price = price - (price * 0.02)
          return price
        end
      else
        price 
      end
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/dealerships_controller.rb
class DealershipsController < ApplicationController
  before_action :set_dealership, only: %i[ show edit update destroy ]

  # GET /dealerships or /dealerships.json
  def index
    @dealerships = Dealership.all
  end

  # GET /dealerships/1 or /dealerships/1.json
  def show
  end

  # GET /dealerships/new
  def new
    @dealership = Dealership.new
  end

  # GET /dealerships/1/edit
  def edit
  end

  # POST /dealerships or /dealerships.json
  def create
    @dealership = Dealership.new(dealership_params)

    respond_to do |format|
      if @dealership.save
        format.html { redirect_to @dealership, notice: "Dealership was successfully created." }
        format.json { render :show, status: :created, location: @dealership }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @dealership.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dealerships/1 or /dealerships/1.json
  def update
    respond_to do |format|
      if @dealership.update(dealership_params)
        format.html { redirect_to @dealership, notice: "Dealership was successfully updated." }
        format.json { render :show, status: :ok, location: @dealership }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @dealership.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dealerships/1 or /dealerships/1.json
  def destroy
    @dealership.destroy
    respond_to do |format|
      format.html { redirect_to dealerships_url, notice: "Dealership was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dealership
      @dealership = Dealership.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def dealership_params
      params.require(:dealership).permit(:name, :address, :user_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/inventories_controller.rb
class InventoriesController < ApplicationController
  before_action :set_inventory, only: %i[ show edit update destroy ]

  # GET /inventories or /inventories.json
  def index
    @inventories = Inventory.all
  end

  # GET /inventories/1 or /inventories/1.json
  def show
  end

  # GET /inventories/new
  def new
    @inventory = Inventory.new
  end

  # GET /inventories/1/edit
  def edit
  end

  # POST /inventories or /inventories.json
  def create
    @inventory = Inventory.new(inventory_params)

    respond_to do |format|
      if @inventory.save
        format.html { redirect_to @inventory, notice: "Inventory was successfully created." }
        format.json { render :show, status: :created, location: @inventory }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @inventory.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /inventories/1 or /inventories/1.json
  def update
    respond_to do |format|
      if @inventory.update(inventory_params)
        format.html { redirect_to @inventory, notice: "Inventory was successfully updated." }
        format.json { render :show, status: :ok, location: @inventory }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @inventory.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /inventories/1 or /inventories/1.json
  def destroy
    @inventory.destroy
    respond_to do |format|
      format.html { redirect_to inventories_url, notice: "Inventory was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_inventory
      @inventory = Inventory.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def inventory_params
      params.require(:inventory).permit(:carmodel, :price, :status, :dealership_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dealerships_helper.rb
module DealershipsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/inventories_helper.rb
module InventoriesHelper
end

app/views/dealerships/_form.html.erb
<%= form_with(model: dealership) do |form| %>
  <% if dealership.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(dealership.errors.count, "error") %> prohibited this dealership from being saved:</h2>

      <ul>
        <% dealership.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address %>
  </div>

  

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/dealerships/edit.html.erb
<h1>Editing Dealership</h1>

<%= render 'form', dealership: @dealership %>

<%= link_to 'Show', @dealership %> |
<%= link_to 'Back', dealerships_path %>

app/views/dealerships/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Dealerships</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @dealerships.each do |dealership| %>
      <tr>
        <td><%= dealership.name %></td>
        <td><%= dealership.address %></td>
        <td><%= link_to 'Show', dealership %></td>
      <%if current_user && current_user.admin? %>
        <td><%= link_to 'Edit', edit_dealership_path(dealership) %></td>
        <td><%= link_to 'Destroy', dealership, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Dealership', new_dealership_path %>

app/views/dealerships/new.html.erb
<h1>New Dealership</h1>

   
<%= render 'form', dealership: @dealership %>
   

<%= link_to 'Back', dealerships_path %>

app/views/dealerships/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @dealership.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @dealership.address %>
</p>


<%if current_user && current_user.admin? %>
  <%= link_to 'Edit', edit_dealership_path(@dealership) %>
<% end %>
<%= link_to 'Back', dealerships_path %>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to "Car-Invent", root_path , class:"navbar-brand" %>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
    
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <% if current_user%>
          
          <li class="nav-item">
          <%= link_to "Inventory", inventories_path , class:"nav-link" %>
        </li>

        <li class="nav-item">
          <%= link_to "Dealer",   dealerships_path , class:"nav-link" %>
        </li>

          <li class="nav-item">
            <%= link_to "Edit Profile",  edit_user_registration_path , class:"nav-link" %>
          </li>
          
        
        <li class="nav-item">
        <%= link_to "Sign Out",  destroy_user_session_path , method: :delete, class:"nav-link" %>
      </li>
        
        <% else %>

          <li class="nav-item">
            <%= link_to "Sign In",  new_user_session_path , class:"nav-link" %>
          </li>

            <li class="nav-item">
            <%= link_to "Sign Up",  new_user_registration_path , class:"nav-link" %>
          </li>
          
        <% end %>

      <%if current_user && current_user.admin? %>

            <li class="nav-item">
              <%= link_to "Add Dealer", new_dealership_path , class:"nav-link" %>
            </li>

            <li class="nav-item">
              <%= link_to "Add Inventory", new_inventory_path , class:"nav-link" %>
            </li>
            
            <li class="nav-item">
          <%= link_to "Add Dealer", new_dealership_path , class:"nav-link" %>
        </li>
      <% end %>



      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/home/index.html.erb
Hello 

app/views/inventories/_form.html.erb
<%= form_with(model: inventory) do |form| %>
  <% if inventory.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(inventory.errors.count, "error") %> prohibited this inventory from being saved:</h2>

      <ul>
        <% inventory.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :carmodel %>
    <%= form.text_field :carmodel %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.number_field :price %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.text_field :status %>
  </div>


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/inventories/edit.html.erb
<h1>Editing Inventory</h1>

<%= render 'form', inventory: @inventory %>

<%= link_to 'Show', @inventory %> |
<%= link_to 'Back', inventories_path %>

app/views/inventories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Inventories</h1>

<table>
  <thead>
    <tr>
      <th>Carmodel</th>
      <th>Price</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @inventories.each do |inventory| %>
      <tr>
        <td><%= inventory.carmodel %></td>
        <td><%= inventory.price %></td>
        <td><%= inventory.status %></td>
        <td><%= link_to 'Show', inventory %></td>
      <%if current_user && current_user.admin? %>
        <td><%= link_to 'Edit', edit_inventory_path(inventory) %></td>
        <td><%= link_to 'Destroy', inventory, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Inventory', new_inventory_path %>

app/views/inventories/new.html.erb
<h1>New Inventory</h1>

<%= render 'form', inventory: @inventory %>

<%= link_to 'Back', inventories_path %>

app/views/inventories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Carmodel:</strong>
  <%= @inventory.carmodel %>
</p>

<p>
  <strong>Price:</strong>
  <%= @inventory.price %>
</p>

<p>
  <strong>Status:</strong>
  <%= @inventory.status %>
</p>


<%if current_user && current_user.admin? %>
<%= link_to 'Edit', edit_inventory_path(@inventory) %>
<% end %> |
<%= link_to 'Back', inventories_path %>

app/views/layouts/_alert.html.erb
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <title>CarsInventory</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <title>Hello, world!</title>
  </head>
  <body>
    <%= render 'home/header' %>
    <%= render 'layouts/alert' %>
    <div class="container">
      <%= yield %>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>

  </body>
</html>